ekf_odom:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.2
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # Wheel odom 
    odom0: /wheel/odom
    odom0_config: [ false, false, false,  # x y z
                    false, false, false,  # roll pitch yaw
                    true,  true,  false,  # vx vy vz
                    false, false, true,   # vroll vpitch vyaw
                    false, false, false]  # ax ay az
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10
    odom0_nodelay: true

    # IMU
    imu0: /imu/data
    imu0_config:  [ false, false, false,  # x y z
                    false, false, false,  # roll pitch yaw
                    false, false, false,  # vx vy vz
                    false, false, true,   # vroll vpitch vyaw
                    false, false, false]  # ax ay az
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 100
    imu0_nodelay: true
